[[language]]
name = "nix"
indent.tab-width = 4
indent.unit = "\t"
auto-format = true

[[language]]
name = "rust"
indent.tab-width = 4
indent.unit = "\t"
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "toml"
indent.tab-width = 4
indent.unit = "\t"


[[language]]
name = "python"
indent.tab-width = 4
indent.unit = "\t"
auto-format = true
formatter = { command = "black", args = ["-", "-q"] }
